### ISSUE TITLE
Add Mashbill Grain Sub-editor to mashbill-update.component.html

### ISSUE THREAD

**Issue by TheRobotCarlson** [TheRobotCarlson/Distilled#2]

**Comment by timis** [comment]
At the moment I'm thinking of using a table with each row having a label of each grain and then an input for the quantity of that grain (default being 0) and having some validation for that they all add up to 100. Thoughts?

**Comment by TheRobotCarlson** [comment]
@timis I think that would work best

**Comment by timis** [comment]
Basically finished. I'd like to add a way for it to not accept when quantities do not add up to 100
